//! Create work item reporting schemas

use log::{debug, info};
use percent_encoding::utf8_percent_encode;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::PATH_SEGMENT;
use crate::safe_outputs::{
    ExecutionContext, ExecutionResult, Executor, ToolResult, Validate, anyhow_to_mcp_error,
};
use crate::sanitize::sanitize_markdown;
use crate::sanitize::{SanitizeContent, sanitize as sanitize_text, sanitize_config};
use crate::secure::{AdoWorkItemFieldRef, WorkItemTemporaryId};
use ado_aw_derive::SanitizeConfig;
use anyhow::{Context, ensure};

/// Parameters for creating a work item
#[derive(Debug, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CreateWorkItemParams {
    /// A concise title for the work item; less than 64 characters
    pub title: String,

    /// Work item description in markdown format. Use headings, lists, code blocks, and other markdown formatting. Ensure adequate content > 30 characters.
    pub description: String,

    /// Tags to apply to the work item. May be subject to an operator-configured
    /// allowlist (`allowed-tags` in front matter). Each tag must not contain a
    /// semicolon (ADO uses semicolons as tag separators).
    #[serde(default)]
    pub tags: Vec<String>,

}

impl Validate for CreateWorkItemParams {
    fn validate(&self) -> anyhow::Result<()> {
        ensure!(self.title.len() > 5, "title must be more than 5 characters");
        ensure!(
            self.description.len() > 30,
            "description must be more than 30 characters"
        );
        for tag in &self.tags {
            ensure!(
                !tag.contains(';'),
                "Tag '{}' contains a semicolon, which is not allowed \
                 (ADO uses semicolons as tag separators)",
                tag
            );
        }
        Ok(())
    }
}

/// Persisted proposal for creating a work item.
///
/// Unlike the agent-facing parameters, this always carries the temporary ID
/// generated by the SafeOutputs MCP server.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct CreateWorkItemResult {
    pub name: String,
    pub title: String,
    pub description: String,
    /// Agent-provided tags (validated against allowed-tags at execution time).
    #[serde(default)]
    pub tags: Vec<String>,
    pub temporary_id: WorkItemTemporaryId,
}

impl ToolResult for CreateWorkItemResult {
    const NAME: &'static str = "create-work-item";
    const REQUIRES_WRITE: bool = true;
}

impl TryFrom<(CreateWorkItemParams, WorkItemTemporaryId)> for CreateWorkItemResult {
    type Error = rmcp::ErrorData;

    fn try_from(
        (params, temporary_id): (CreateWorkItemParams, WorkItemTemporaryId),
    ) -> Result<Self, Self::Error> {
        params.validate().map_err(anyhow_to_mcp_error)?;
        Ok(Self {
            name: Self::NAME.to_string(),
            title: params.title,
            description: params.description,
            tags: params.tags,
            temporary_id,
        })
    }
}

impl SanitizeContent for CreateWorkItemResult {
    fn sanitize_content_fields(&mut self) {
        self.title = sanitize_text(&self.title);
        self.description = sanitize_markdown(&self.description);
        for tag in &mut self.tags {
            *tag = sanitize_config(tag);
        }
    }
}

/// Configuration for the create_work_item tool (specified in front matter)
///
/// Example front matter:
/// ```yaml
/// safe-outputs:
///   create_work_item:
///     work_item_type: Task
///     area_path: "MyProject\\MyTeam"
///     iteration_path: "MyProject\\Sprint 1"
///     assignee: "user@example.com"
///     tags:
///       - agent-created
///       - automated
///     allowed-tags:
///       - "agent-*"
///       - automated
///     artifact_link:
///       enabled: true
///       repository: "my-repo-name"  # optional, defaults to current repo
///       branch: "main"              # optional, defaults to "main"
/// ```
#[derive(Debug, Clone, SanitizeConfig, Serialize, Deserialize)]
pub struct CreateWorkItemConfig {
    /// Work item type (default: "Task")
    #[serde(default = "default_work_item_type", rename = "work-item-type")]
    pub work_item_type: String,

    /// Field reference name that receives the agent-provided description.
    /// Defaults to System.Description, except Bug work items default to
    /// Microsoft.VSTS.TCM.ReproSteps.
    #[serde(default, rename = "description-field")]
    #[sanitize_config(skip)]
    pub description_field: Option<AdoWorkItemFieldRef>,

    /// Area path for the work item
    #[serde(default, rename = "area-path")]
    pub area_path: Option<String>,

    /// Iteration path for the work item
    #[serde(default, rename = "iteration-path")]
    pub iteration_path: Option<String>,

    /// User to assign the work item to (email or display name)
    #[serde(default)]
    pub assignee: Option<String>,

    /// Static tags always applied to the work item (regardless of agent input)
    #[serde(default)]
    pub tags: Vec<String>,

    /// Allowlist of tags the agent is permitted to use via the `tags` parameter.
    /// If empty, any agent-provided tags are accepted.
    /// Supports prefix wildcards: entries ending with `*` match by prefix
    /// (e.g., `"agent-*"` matches `"agent-created"`, `"agent-review"`, etc.).
    #[serde(default, rename = "allowed-tags")]
    pub allowed_tags: Vec<String>,

    /// Additional custom fields as key-value pairs
    /// Keys should be the full field reference name (e.g., "Custom.MyField")
    #[serde(default, rename = "custom-fields")]
    #[sanitize_config(sanitize_keys)]
    pub custom_fields: std::collections::HashMap<String, String>,

    /// Artifact link configuration for GitHub Copilot integration
    #[serde(default, rename = "artifact-link")]
    #[sanitize_config(nested)]
    pub artifact_link: ArtifactLinkConfig,

    /// Whether to include agent execution stats in the output (default: true).
    #[serde(
        default = "crate::agent_stats::default_include_stats",
        rename = "include-stats"
    )]
    pub include_stats: bool,
}

/// Configuration for artifact links (repository linking for GitHub Copilot)
#[derive(Debug, Clone, SanitizeConfig, Serialize, Deserialize)]
pub struct ArtifactLinkConfig {
    /// Whether to add an artifact link to the work item (default: false)
    #[serde(default)]
    pub enabled: bool,

    /// Override the repository name (defaults to BUILD_REPOSITORY_NAME from environment)
    /// The repository ID will be resolved automatically via Azure DevOps API
    #[serde(default)]
    pub repository: Option<String>,

    /// Branch name to link to (default: "main")
    #[serde(default = "default_branch")]
    pub branch: String,
}

fn default_branch() -> String {
    "main".to_string()
}

impl Default for ArtifactLinkConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            repository: None,
            branch: default_branch(),
        }
    }
}

impl Default for CreateWorkItemConfig {
    fn default() -> Self {
        Self {
            work_item_type: default_work_item_type(),
            description_field: None,
            area_path: None,
            iteration_path: None,
            assignee: None,
            tags: Vec::new(),
            allowed_tags: Vec::new(),
            custom_fields: std::collections::HashMap::new(),
            artifact_link: ArtifactLinkConfig::default(),
            include_stats: true,
        }
    }
}

fn default_work_item_type() -> String {
    "Task".to_string()
}

const SYSTEM_DESCRIPTION_FIELD: &str = "System.Description";
const BUG_REPRO_STEPS_FIELD: &str = "Microsoft.VSTS.TCM.ReproSteps";

fn default_description_field_for(work_item_type: &str) -> &'static str {
    if work_item_type.eq_ignore_ascii_case("Bug") {
        BUG_REPRO_STEPS_FIELD
    } else {
        SYSTEM_DESCRIPTION_FIELD
    }
}

fn description_field_for(config: &CreateWorkItemConfig) -> &str {
    config
        .description_field
        .as_ref()
        .map(AdoWorkItemFieldRef::as_str)
        .unwrap_or_else(|| default_description_field_for(&config.work_item_type))
}

/// Build a field patch operation for work item creation
fn field_op(field: &str, value: impl Into<String>) -> serde_json::Value {
    serde_json::json!({
        "op": "add",
        "path": format!("/fields/{}", field),
        "value": value.into()
    })
}

/// Build an artifact link relation patch operation
fn artifact_link_op(project: &str, repository_id: &str, branch: &str) -> serde_json::Value {
    // Azure DevOps artifact link URL format for Git branch refs:
    // vstfs:///Git/Ref/{projectId}%2F{repositoryId}%2FGB{branchName}
    // GB prefix indicates a branch (Git Branch)
    let artifact_uri = format!(
        "vstfs:///Git/Ref/{}%2F{}%2FGB{}",
        project, repository_id, branch
    );

    serde_json::json!({
        "op": "add",
        "path": "/relations/-",
        "value": {
            "rel": "ArtifactLink",
            "url": artifact_uri,
            "attributes": {
                "name": "Branch"
            }
        }
    })
}

/// Resolve the artifact link patch op and a human-readable status message.
///
/// Returns `Ok(None)` when artifact linking is disabled.
/// Returns `Ok(Some((op, message)))` when an op was built.
/// Returns `Err(ExecutionResult)` when the caller should short-circuit with a failure.
async fn maybe_build_artifact_link_op(
    client: &reqwest::Client,
    config: &ArtifactLinkConfig,
    ctx: &ExecutionContext,
    org_url: &str,
    project: &str,
    token: &str,
) -> Result<Option<(serde_json::Value, String)>, ExecutionResult> {
    if !config.enabled {
        return Ok(None);
    }

    let repo_name = match config.repository.as_ref().or(ctx.repository_name.as_ref()) {
        Some(name) => name,
        None => {
            return Ok(Some((
                serde_json::Value::Null,
                "skipped: no repository available".to_string(),
            )));
        }
    };

    // Prefer the env-supplied repo ID to avoid an extra API call; fall back to lookup.
    let repo_id = if config.repository.is_none() {
        ctx.repository_id.clone()
    } else {
        None
    };

    let repo_id = match repo_id {
        Some(id) => id,
        None => match resolve_repository_id(client, org_url, project, token, repo_name).await {
            Ok(id) => id,
            Err(e) => {
                return Err(ExecutionResult::failure(format!(
                    "Failed to resolve repository '{}': {}",
                    repo_name, e
                )));
            }
        },
    };

    let op = artifact_link_op(project, &repo_id, &config.branch);
    let message = format!("linked to {}:{}", repo_name, config.branch);
    Ok(Some((op, message)))
}

/// Resolve a repository name to its ID via Azure DevOps API
async fn resolve_repository_id(
    client: &reqwest::Client,
    org_url: &str,
    project: &str,
    token: &str,
    repo_name: &str,
) -> anyhow::Result<String> {
    // GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}?api-version=7.0
    let url = format!(
        "{}/{}/_apis/git/repositories/{}?api-version=7.0",
        org_url.trim_end_matches('/'),
        project,
        repo_name
    );

    let response = client
        .get(&url)
        .basic_auth("", Some(token))
        .send()
        .await
        .context("Failed to query repository")?;

    if response.status().is_success() {
        let body: serde_json::Value = response
            .json()
            .await
            .context("Failed to parse repository response")?;

        body.get("id")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
            .context("Repository response missing 'id' field")
    } else {
        let status = response.status();
        let error_body = response
            .text()
            .await
            .unwrap_or_else(|_| "Unknown error".to_string());

        anyhow::bail!(
            "Failed to resolve repository '{}' (HTTP {}): {}",
            repo_name,
            status,
            error_body
        )
    }
}

#[async_trait::async_trait]
impl Executor for CreateWorkItemResult {
    fn dry_run_summary(&self) -> String {
        format!("create work item: '{}'", self.title)
    }

    async fn execute_impl(&self, ctx: &ExecutionContext) -> anyhow::Result<ExecutionResult> {
        info!("Creating work item: '{}'", self.title);
        debug!(
            "create-work-item: title='{}', description length={}",
            self.title,
            self.description.len()
        );
        debug!("Description length: {} chars", self.description.len());

        let org_url = ctx
            .ado_org_url
            .as_ref()
            .context("AZURE_DEVOPS_ORG_URL not set")?;
        let project = ctx
            .ado_project
            .as_ref()
            .context("SYSTEM_TEAMPROJECT not set")?;
        let token = ctx
            .access_token
            .as_ref()
            .context("No access token available (SYSTEM_ACCESSTOKEN or AZURE_DEVOPS_EXT_PAT)")?;
        debug!("ADO org: {}, project: {}", org_url, project);

        // Get tool-specific configuration
        let config: CreateWorkItemConfig = ctx.get_tool_config("create-work-item")?;
        debug!("Work item type: {}", config.work_item_type);
        debug!("Area path: {:?}", config.area_path);
        debug!("Iteration path: {:?}", config.iteration_path);
        debug!("Assignee (config): {:?}", config.assignee);
        if ctx.has_resolved_work_item(&self.temporary_id)? {
            return Ok(ExecutionResult::failure(format!(
                "temporary_id '{}' was already used in this run",
                self.temporary_id.canonical()
            )));
        }

        // Validate agent-provided tags against allowed-tags (if configured)
        if !self.tags.is_empty() && !config.allowed_tags.is_empty() {
            let disallowed: Vec<_> = self
                .tags
                .iter()
                .filter(|tag| {
                    !config
                        .allowed_tags
                        .iter()
                        .any(|pattern| super::tag_matches_pattern(tag, pattern))
                })
                .collect();
            if !disallowed.is_empty() {
                return Ok(ExecutionResult::failure(format!(
                    "Agent-provided tags not in allowed-tags: {}",
                    disallowed
                        .iter()
                        .map(|t| t.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                )));
            }
        }

        // Build the Azure DevOps REST API URL for creating work items
        // POST https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/${type}?api-version=7.0
        debug!("Building work item creation request");
        let url = format!(
            "{}/{}/_apis/wit/workitems/${}?api-version=7.0",
            org_url.trim_end_matches('/'),
            utf8_percent_encode(project, PATH_SEGMENT),
            utf8_percent_encode(&config.work_item_type, PATH_SEGMENT),
        );
        debug!("API URL: {}", url);

        // Build the patch document for work item creation
        let description_with_stats =
            crate::agent_stats::append_stats_to_body(&self.description, ctx, config.include_stats);
        let description_field = description_field_for(&config);
        let mut patch_doc = vec![
            field_op("System.Title", &self.title),
            field_op(description_field, &description_with_stats),
            // Tell Azure DevOps the description is markdown
            serde_json::json!({
                "op": "add",
                "path": format!("/multilineFieldsFormat/{description_field}"),
                "value": "Markdown"
            }),
        ];

        // Add optional configured fields
        if let Some(area_path) = &config.area_path {
            patch_doc.push(field_op("System.AreaPath", area_path));
        }
        if let Some(iteration_path) = &config.iteration_path {
            patch_doc.push(field_op("System.IterationPath", iteration_path));
        }
        if let Some(assignee) = config.assignee.as_deref() {
            let assignee = match super::normalize_work_item_assignee(
                assignee,
                "safe-outputs.create-work-item.assignee",
            ) {
                Ok(assignee) => assignee,
                Err(error) => return Ok(ExecutionResult::failure(error.to_string())),
            };
            patch_doc.push(field_op("System.AssignedTo", assignee));
        }
        // Merge static config tags with validated agent-provided tags (dedup, case-insensitive)
        let mut all_tags = config.tags.clone();
        for tag in &self.tags {
            if !all_tags.iter().any(|t| t.eq_ignore_ascii_case(tag)) {
                all_tags.push(tag.clone());
            }
        }
        if !all_tags.is_empty() {
            patch_doc.push(field_op("System.Tags", all_tags.join("; ")));
        }

        // Add any custom fields
        for (field, value) in &config.custom_fields {
            patch_doc.push(field_op(field, value));
        }

        // Create HTTP client (needed for both work item creation and optional repo lookup)
        let client = reqwest::Client::new();

        // Add artifact link if configured (included in creation request)
        let artifact_link_included = match maybe_build_artifact_link_op(
            &client,
            &config.artifact_link,
            ctx,
            org_url,
            project,
            token,
        )
        .await
        {
            Err(failure) => return Ok(failure),
            Ok(None) => None,
            Ok(Some((op, message))) => {
                if !op.is_null() {
                    patch_doc.push(op);
                }
                Some(message)
            }
        };

        // Make the API call
        info!("Sending work item creation request to ADO");
        let response = client
            .post(&url)
            .header("Content-Type", "application/json-patch+json")
            .basic_auth("", Some(token))
            .json(&patch_doc)
            .send()
            .await
            .context("Failed to send request to Azure DevOps")?;

        if response.status().is_success() {
            let body: serde_json::Value = response
                .json()
                .await
                .context("Failed to parse response JSON")?;

            let Some(work_item_id) = body
                .get("id")
                .and_then(|v| v.as_u64())
                .filter(|id| *id > 0)
            else {
                return Ok(ExecutionResult::failure(
                    "Azure DevOps create-work-item response contained no positive work-item ID",
                ));
            };
            let work_item_url = body
                .get("_links")
                .and_then(|l| l.get("html"))
                .and_then(|h| h.get("href"))
                .and_then(|h| h.as_str())
                .unwrap_or("");

            info!("Work item created: #{} - {}", work_item_id, work_item_url);

            if let Err(error) = ctx.register_resolved_work_item(
                &self.temporary_id,
                crate::safe_outputs::ResolvedWorkItem {
                    id: work_item_id,
                    url: work_item_url.to_string(),
                },
            ) {
                return Ok(ExecutionResult::failure_with_data(
                    format!(
                        "Created work item #{} but failed to register temporary_id '{}': {}",
                        work_item_id,
                        self.temporary_id.canonical(),
                        crate::sanitize::neutralize_pipeline_commands(&error.to_string())
                    ),
                    serde_json::json!({
                        "id": work_item_id,
                        "url": work_item_url,
                        "temporary_id": self.temporary_id.canonical(),
                    }),
                ));
            }

            let message = match &artifact_link_included {
                Some(link_msg) => format!(
                    "Created work item #{}: {} (artifact link: {})",
                    work_item_id, self.title, link_msg
                ),
                None => format!("Created work item #{}: {}", work_item_id, self.title),
            };

            Ok(ExecutionResult::success_with_data(
                message,
                serde_json::json!({
                    "id": work_item_id,
                    "url": work_item_url,
                    "project": project,
                    "type": config.work_item_type,
                    "artifact_link": artifact_link_included,
                    "temporary_id": self.temporary_id.canonical(),
                }),
            ))
        } else {
            let status = response.status();
            let error_body = response
                .text()
                .await
                .unwrap_or_else(|_| "Unknown error".to_string());

            Ok(ExecutionResult::failure(format!(
                "Failed to create work item (HTTP {}): {}",
                status, error_body
            )))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::safe_outputs::ToolResult;

    #[test]
    fn test_result_has_correct_name() {
        assert_eq!(CreateWorkItemResult::NAME, "create-work-item");
    }

    #[test]
    fn test_params_deserializes() {
        let json = r#"{"title": "Fix bug", "description": "This is a detailed description of the work item to be created."}"#;
        let params: CreateWorkItemParams = serde_json::from_str(json).unwrap();
        assert_eq!(params.title, "Fix bug");
        assert!(params.description.contains("detailed description"));
    }

    #[test]
    fn test_params_rejects_caller_supplied_temporary_id() {
        let json = r##"{
            "title": "Fix a real bug",
            "description": "This is a detailed description of the work item to be created.",
            "temporary_id": "#aw_caller1"
        }"##;
        let error = serde_json::from_str::<CreateWorkItemParams>(json).unwrap_err();
        assert!(error.to_string().contains("unknown field `temporary_id`"));
    }

    #[test]
    fn test_params_converts_to_result() {
        let params = CreateWorkItemParams {
            title: "Implement feature".to_string(),
            description: "This is a sufficiently long description for the work item.".to_string(),
            tags: vec![],
        };
        let result: CreateWorkItemResult = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into()
            .unwrap();
        assert_eq!(result.name, "create-work-item");
        assert_eq!(result.title, "Implement feature");
        assert!(result.description.contains("sufficiently long"));
    }

    #[test]
    fn test_validation_rejects_short_title() {
        let params = CreateWorkItemParams {
            title: "Hi".to_string(),
            description: "This is a sufficiently long description for the work item.".to_string(),
            tags: vec![],
        };
        let result: Result<CreateWorkItemResult, _> = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into();
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("title must be more than 5 characters"),
            "Expected title length error, got: {err}"
        );
    }

    #[test]
    fn test_validation_rejects_short_description() {
        let params = CreateWorkItemParams {
            title: "Valid title here".to_string(),
            description: "Too short".to_string(),
            tags: vec![],
        };
        let result: Result<CreateWorkItemResult, _> = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into();
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("description must be more than 30 characters"),
            "Expected description length error, got: {err}"
        );
    }

    #[test]
    fn test_validation_rejects_tag_with_semicolon() {
        let params = CreateWorkItemParams {
            title: "Valid title here".to_string(),
            description: "This is a sufficiently long description for the work item.".to_string(),
            tags: vec!["tag-one; tag-two".to_string()],
        };
        let result: Result<CreateWorkItemResult, _> = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into();
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("semicolon"),
            "Expected semicolon error, got: {err}"
        );
    }

    #[test]
    fn test_params_with_tags_converts_to_result() {
        let params = CreateWorkItemParams {
            title: "Implement feature".to_string(),
            description: "This is a sufficiently long description for the work item.".to_string(),
            tags: vec!["agent-created".to_string(), "automated".to_string()],
        };
        let result: CreateWorkItemResult = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into()
            .unwrap();
        assert_eq!(result.tags, vec!["agent-created", "automated"]);
    }

    #[test]
    fn test_result_serializes_correctly() {
        let params = CreateWorkItemParams {
            title: "Test work item".to_string(),
            description: "A description that is definitely longer than thirty characters."
                .to_string(),
            tags: vec![],
        };
        let result: CreateWorkItemResult = (
            params,
            WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        )
            .try_into()
            .unwrap();
        let json = serde_json::to_string(&result).unwrap();

        assert!(json.contains(r#""name":"create-work-item""#));
        assert!(json.contains(r#""title":"Test work item""#));
    }

    #[test]
    fn test_config_defaults() {
        let config = CreateWorkItemConfig::default();
        assert_eq!(config.work_item_type, "Task");
        assert_eq!(description_field_for(&config), "System.Description");
        assert!(config.area_path.is_none());
        assert!(config.iteration_path.is_none());
        assert!(config.assignee.is_none());
        assert!(config.tags.is_empty());
        assert!(config.allowed_tags.is_empty());
        assert!(config.custom_fields.is_empty());
    }

    #[test]
    fn test_config_deserializes_from_yaml() {
        let yaml = r#"
work-item-type: Bug
description-field: Custom.Body
area-path: "MyProject\\MyTeam"
assignee: "user@example.com"
tags:
  - agent-created
  - automated
allowed-tags:
  - "agent-*"
  - review
custom-fields:
  Custom.Priority: "High"
"#;
        let config: CreateWorkItemConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(config.work_item_type, "Bug");
        assert_eq!(config.description_field.as_deref(), Some("Custom.Body"));
        assert_eq!(description_field_for(&config), "Custom.Body");
        assert_eq!(config.area_path, Some("MyProject\\MyTeam".to_string()));
        assert_eq!(config.assignee, Some("user@example.com".to_string()));
        assert_eq!(config.tags, vec!["agent-created", "automated"]);
        assert_eq!(config.allowed_tags, vec!["agent-*", "review"]);
        assert_eq!(
            config.custom_fields.get("Custom.Priority"),
            Some(&"High".to_string())
        );
    }

    #[test]
    fn test_config_partial_deserialize_uses_defaults() {
        let yaml = r#"
tags:
  - my-tag
"#;
        let config: CreateWorkItemConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(config.work_item_type, "Task"); // default
        assert_eq!(description_field_for(&config), "System.Description");
        assert!(config.area_path.is_none()); // default
        assert_eq!(config.tags, vec!["my-tag"]);
        assert!(config.allowed_tags.is_empty()); // default
    }

    #[test]
    fn test_bug_defaults_description_field_to_repro_steps() {
        let config: CreateWorkItemConfig = serde_yaml::from_str("work-item-type: Bug\n").unwrap();
        assert_eq!(
            description_field_for(&config),
            "Microsoft.VSTS.TCM.ReproSteps"
        );
    }

    #[test]
    fn test_config_rejects_invalid_description_field() {
        let error =
            serde_yaml::from_str::<CreateWorkItemConfig>("description-field: System/Description\n")
                .unwrap_err();

        assert!(error.to_string().contains("work item field"));
    }

    #[test]
    fn test_result_sanitization_preserves_description_html() {
        let mut result = CreateWorkItemResult {
            name: CreateWorkItemResult::NAME.to_string(),
            title: "Test work item".to_string(),
            description: "<h2>Hi</h2><p>x &lt;string&gt; y</p>".to_string(),
            tags: Vec::new(),
            temporary_id: WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        };

        result.sanitize_content_fields();

        assert_eq!(result.description, "<h2>Hi</h2><p>x &lt;string&gt; y</p>");
    }

    #[tokio::test]
    async fn test_execute_bug_uses_repro_steps_and_preserves_html() {
        use std::collections::HashMap;
        use wiremock::matchers::{body_json, method, path};
        use wiremock::{Mock, MockServer, ResponseTemplate};

        let server = MockServer::start().await;
        let expected_patch = serde_json::json!([
            {
                "op": "add",
                "path": "/fields/System.Title",
                "value": "Bug with visible body"
            },
            {
                "op": "add",
                "path": "/fields/Microsoft.VSTS.TCM.ReproSteps",
                "value": "<h2>Hi</h2><p>x &lt;string&gt; y</p>"
            },
            {
                "op": "add",
                "path": "/multilineFieldsFormat/Microsoft.VSTS.TCM.ReproSteps",
                "value": "Markdown"
            }
        ]);
        Mock::given(method("POST"))
            .and(path("/Project/_apis/wit/workitems/$Bug"))
            .and(body_json(expected_patch))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": 42,
                "_links": {
                    "html": {
                        "href": "https://example.test/workitems/42"
                    }
                }
            })))
            .mount(&server)
            .await;

        let ctx = ExecutionContext {
            ado_org_url: Some(server.uri()),
            ado_project: Some("Project".to_string()),
            access_token: Some("token".to_string()),
            tool_configs: HashMap::from([(
                "create-work-item".to_string(),
                serde_json::json!({
                    "work-item-type": "Bug",
                    "include-stats": false
                }),
            )]),
            ..Default::default()
        };
        let mut result = CreateWorkItemResult {
            name: CreateWorkItemResult::NAME.to_string(),
            title: "Bug with visible body".to_string(),
            description: "<h2>Hi</h2><p>x &lt;string&gt; y</p>".to_string(),
            tags: Vec::new(),
            temporary_id: WorkItemTemporaryId::parse("#aw_test1").unwrap(),
        };

        let execution = result.execute_sanitized(&ctx).await.unwrap();

        assert!(execution.success, "{}", execution.message);
    }
}
