//! Agentic pipeline detection.
//!
//! Scans a directory for compiled pipeline YAML files that were generated by `ado-aw`.
//! Detection relies on the `# @ado-aw` header comment that the compiler prepends to all output.

use anyhow::{Context, Result};
use log::{debug, info};
use serde::Deserialize;
use std::path::{Path, PathBuf};
use tokio::io::AsyncBufReadExt;

use crate::compile::HEADER_MARKER;

/// Metadata extracted from an agentic pipeline header comment.
#[derive(Debug, Clone)]
pub struct DetectedPipeline {
    /// Path to the YAML file (relative to the scan root)
    pub yaml_path: PathBuf,
    /// Source markdown file path from the header (e.g., `agents/my-agent.md`)
    pub source: String,
    /// Compiler version that generated this pipeline
    pub version: String,
}

/// Scan a directory for agentic pipeline YAML files.
///
/// Recursively walks `root` looking for `*.yml` and `*.yaml` files whose first
/// few lines contain the `# @ado-aw` marker. Returns metadata extracted from
/// each detected pipeline's header.
pub async fn detect_pipelines(root: &Path) -> Result<Vec<DetectedPipeline>> {
    info!("Scanning for agentic pipelines in: {}", root.display());
    let mut results = Vec::new();
    scan_directory(root, root, &mut results).await?;
    info!("Found {} agentic pipeline(s)", results.len());
    Ok(results)
}

/// Recursively scan a directory, collecting detected pipelines.
fn scan_directory<'a>(
    dir: &'a Path,
    root: &'a Path,
    results: &'a mut Vec<DetectedPipeline>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send + 'a>> {
    Box::pin(async move {
        let mut entries = tokio::fs::read_dir(dir)
            .await
            .with_context(|| format!("Failed to read directory: {}", dir.display()))?;

        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            let file_type = entry.file_type().await?;

            if file_type.is_dir() {
                // Skip hidden directories (except .azdo which commonly contains pipelines)
                // and common non-pipeline directories
                let name = entry.file_name();
                let name_str = name.to_string_lossy();
                if (name_str.starts_with('.') && name_str != ".azdo")
                    || name_str == "node_modules"
                    || name_str == "target"
                {
                    continue;
                }
                scan_directory(&path, root, results).await?;
            } else if file_type.is_file() {
                if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                    if ext == "yml" || ext == "yaml" {
                        if let Some(pipeline) = try_detect_pipeline(&path, root).await? {
                            debug!("Detected agentic pipeline: {}", path.display());
                            results.push(pipeline);
                        }
                    }
                }
            }
        }

        Ok(())
    })
}

/// Check if a YAML file is an agentic pipeline and extract its metadata.
///
/// Reads only the first 5 lines of the file for performance — the `@ado-aw`
/// marker is always in the first two lines of compiled output.
async fn try_detect_pipeline(
    file_path: &Path,
    root: &Path,
) -> Result<Option<DetectedPipeline>> {
    let file = match tokio::fs::File::open(file_path).await {
        Ok(f) => f,
        Err(e) => {
            debug!(
                "Skipping {} (open error: {})",
                file_path.display(),
                e
            );
            return Ok(None);
        }
    };

    let reader = tokio::io::BufReader::new(file);
    let mut lines = reader.lines();
    let mut line_count = 0;

    while let Ok(Some(line)) = lines.next_line().await {
        line_count += 1;
        if line_count > 5 {
            break;
        }

        if let Some(metadata) = parse_header_line(&line) {
            let relative_path = file_path
                .strip_prefix(root)
                .unwrap_or(file_path)
                .to_path_buf();

            return Ok(Some(DetectedPipeline {
                yaml_path: relative_path,
                source: metadata.source,
                version: metadata.version,
            }));
        }
    }

    Ok(None)
}

/// Prefix of the machine-readable marker emitted into every compiled
/// pipeline by the always-on `ado-aw-marker` compiler extension.
///
/// The marker is a `# ado-aw-metadata: { … JSON … }` line embedded
/// inside the bash body of an injected Agent-job prepare step. The
/// step body (unlike top-of-file YAML comments) survives ADO Pipeline
/// Preview expansion, so this prefix is the canonical surface
/// project-scope discovery searches for in expanded YAML.
pub const MARKER_STEP_PREFIX: &str = "# ado-aw-metadata:";

/// Parsed metadata from a `# ado-aw-metadata: {…}` marker step line.
///
/// The schema is forward-compatible: unknown JSON fields are ignored,
/// and missing fields fall through to defaults (empty string / zero).
/// Callers that need a specific field should check it explicitly.
#[derive(Debug, Clone, Default, Deserialize, PartialEq, Eq)]
pub struct MarkerMetadata {
    /// Schema version; `1` for the initial release.
    #[serde(default)]
    pub schema: u32,
    /// Source markdown path, normalised forward-slash form (e.g.
    /// `agents/release-readiness.md`).
    #[serde(default)]
    pub source: String,
    /// ADO organisation name the source markdown was compiled in
    /// (e.g. `myorg`). Lowercased at emit time. Combined with
    /// [`MarkerMetadata::repo`] this disambiguates the marker's
    /// `source` field when two repos in the same ADO project happen
    /// to have files of the same name (e.g. both define
    /// `agents/foo.md`). Empty string when the compiler ran outside
    /// an ADO checkout (rare in production thanks to the
    /// non-GitHub-remote guard).
    #[serde(default)]
    pub org: String,
    /// ADO repository name the source markdown was compiled in
    /// (e.g. `templates-a`). Lowercased at emit time. See
    /// [`MarkerMetadata::org`] for rationale. Empty string when the
    /// compiler ran outside an ADO checkout.
    #[serde(default)]
    pub repo: String,
    /// Compiler version that produced this YAML (`CARGO_PKG_VERSION`).
    #[serde(default)]
    pub version: String,
    /// Compile target: `standalone` / `1es` / `job` / `stage`.
    #[serde(default)]
    pub target: String,
}

/// Scan raw pipeline YAML for `# ado-aw-metadata: {…}` marker lines.
///
/// Returns one [`MarkerMetadata`] per parseable hit. Multiple hits in a
/// single document indicate a consumer pipeline that includes more than
/// one ado-aw-generated template; project-scope discovery uses that to
/// classify the definition as `Consumer`. Malformed JSON entries are
/// skipped (logged at debug) rather than panicking — defensive against
/// future schema drift inside the JSON blob.
///
/// Designed to be called against either:
/// - Raw compiled-on-disk lock-file YAML, or
/// - The `finalYaml` returned by ADO's Pipeline Preview API (which
///   strips top-of-file comments but preserves step bodies).
pub fn parse_marker_step(yaml: &str) -> Vec<MarkerMetadata> {
    let mut results = Vec::new();

    for line in yaml.lines() {
        // Trim leading whitespace; the marker lives inside an indented
        // bash heredoc, so the actual `#` may be indented arbitrarily.
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix(MARKER_STEP_PREFIX) else {
            continue;
        };

        let json_str = rest.trim();
        if !json_str.starts_with('{') {
            // Marker prefix matched but no JSON payload — likely
            // documentation or a non-marker comment. Skip silently.
            continue;
        }

        match serde_json::from_str::<MarkerMetadata>(json_str) {
            Ok(meta) => results.push(meta),
            Err(e) => {
                log::debug!(
                    "Skipping malformed ado-aw-metadata marker: {} (payload: {})",
                    e,
                    json_str
                );
            }
        }
    }

    results
}

/// Parsed metadata from a `# @ado-aw` header line.
pub struct HeaderMetadata {
    pub source: String,
    pub version: String,
}

/// Parse a single line for the `# @ado-aw` marker and extract key=value pairs.
///
/// Expected format: `# @ado-aw source="path/to/agent.md" version=1.2.3`
///
/// The source value is quoted to support paths with spaces. Unquoted values
/// are also accepted for backward compatibility.
pub fn parse_header_line(line: &str) -> Option<HeaderMetadata> {
    let line = line.trim();
    // Require exact marker followed by a space to avoid matching e.g. "# @ado-aw-v2"
    let rest = line.strip_prefix(HEADER_MARKER)?.strip_prefix(' ')?;

    let mut source = String::new();
    let mut version = String::new();

    let mut remaining = rest;
    while !remaining.is_empty() {
        remaining = remaining.trim_start();
        if let Some(after) = remaining.strip_prefix("source=") {
            // Handle quoted value: source="path with spaces"
            if let Some(after_quote) = after.strip_prefix('"') {
                // Find closing quote, skipping escaped quotes (\")
                let mut value = String::new();
                let mut chars = after_quote.char_indices();
                let mut end_pos = after_quote.len();
                while let Some((i, c)) = chars.next() {
                    if c == '\\' {
                        // Consume the escaped character
                        if let Some((_, escaped)) = chars.next() {
                            value.push(escaped);
                        }
                    } else if c == '"' {
                        end_pos = i;
                        break;
                    } else {
                        value.push(c);
                    }
                }
                source = value;
                remaining = if end_pos < after_quote.len() {
                    &after_quote[end_pos + 1..]
                } else {
                    ""
                };
            } else {
                // Unquoted: take until next whitespace
                let end = after.find(' ').unwrap_or(after.len());
                source = after[..end].to_string();
                remaining = &after[end..];
            }
        } else if let Some(after) = remaining.strip_prefix("version=") {
            let end = after.find(' ').unwrap_or(after.len());
            version = after[..end].to_string();
            remaining = &after[end..];
        } else {
            // Skip unknown token
            let end = remaining.find(' ').unwrap_or(remaining.len());
            remaining = &remaining[end..];
        }
    }

    if source.is_empty() && version.is_empty() {
        return None;
    }

    Some(HeaderMetadata { source, version })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_marker_step_single() {
        let yaml = "\
- bash: |
    # ado-aw-metadata: {\"schema\":1,\"source\":\"agents/foo.md\",\"version\":\"0.28.0\",\"target\":\"standalone\"}
    echo hello
  displayName: \"ado-aw\"
";
        let metas = parse_marker_step(yaml);
        assert_eq!(metas.len(), 1);
        assert_eq!(metas[0].schema, 1);
        assert_eq!(metas[0].source, "agents/foo.md");
        assert_eq!(metas[0].version, "0.28.0");
        assert_eq!(metas[0].target, "standalone");
    }

    #[test]
    fn test_parse_marker_step_multiple() {
        // A consumer pipeline pulling in two templates expands to two
        // marker steps in finalYaml.
        let yaml = "\
jobs:
  - job: a
    steps:
      - bash: |
          # ado-aw-metadata: {\"schema\":1,\"source\":\"agents/a.md\",\"version\":\"0.28.0\",\"target\":\"job\"}
          echo a
        displayName: \"ado-aw\"
  - job: b
    steps:
      - bash: |
          # ado-aw-metadata: {\"schema\":1,\"source\":\"agents/b.md\",\"version\":\"0.27.0\",\"target\":\"job\"}
          echo b
        displayName: \"ado-aw\"
";
        let metas = parse_marker_step(yaml);
        assert_eq!(metas.len(), 2);
        let sources: Vec<&str> = metas.iter().map(|m| m.source.as_str()).collect();
        assert!(sources.contains(&"agents/a.md"));
        assert!(sources.contains(&"agents/b.md"));
    }

    #[test]
    fn test_parse_marker_step_no_match_returns_empty() {
        let yaml = "name: foo\njobs:\n  - job: x\n    steps:\n      - bash: echo hi\n";
        assert!(parse_marker_step(yaml).is_empty());
    }

    #[test]
    fn test_parse_marker_step_skips_malformed_json() {
        // The prefix matches but the JSON is broken; the parser must
        // skip silently rather than panic. A valid marker on a later
        // line is still returned.
        let yaml = "\
- bash: |
    # ado-aw-metadata: {not valid json
    # ado-aw-metadata: {\"schema\":1,\"source\":\"agents/ok.md\",\"version\":\"1.0.0\",\"target\":\"stage\"}
";
        let metas = parse_marker_step(yaml);
        assert_eq!(metas.len(), 1);
        assert_eq!(metas[0].source, "agents/ok.md");
    }

    #[test]
    fn test_parse_marker_step_tolerates_extra_json_fields() {
        // Forward-compatibility: an unknown future field shouldn't
        // break the parser.
        let yaml = "    # ado-aw-metadata: {\"schema\":2,\"source\":\"agents/x.md\",\"version\":\"1.0.0\",\"target\":\"standalone\",\"future_field\":[1,2,3]}\n";
        let metas = parse_marker_step(yaml);
        assert_eq!(metas.len(), 1);
        assert_eq!(metas[0].source, "agents/x.md");
        assert_eq!(metas[0].schema, 2);
    }

    #[test]
    fn test_parse_marker_step_ignores_prefix_without_json() {
        let yaml = "# ado-aw-metadata: (manual documentation note, not a marker)\n";
        assert!(parse_marker_step(yaml).is_empty());
    }

    #[test]
    fn test_parse_header_line_valid() {
        let line = "# @ado-aw source=agents/my-agent.md version=0.3.2";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/my-agent.md");
        assert_eq!(meta.version, "0.3.2");
    }

    #[test]
    fn test_parse_header_line_quoted_source() {
        let line = r#"# @ado-aw source="agents/my-agent.md" version=0.3.2"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/my-agent.md");
        assert_eq!(meta.version, "0.3.2");
    }

    #[test]
    fn test_parse_header_line_quoted_source_with_spaces() {
        let line = r#"# @ado-aw source="my agents/my agent.md" version=0.5.0"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "my agents/my agent.md");
        assert_eq!(meta.version, "0.5.0");
    }

    #[test]
    fn test_parse_header_line_reordered() {
        let line = "# @ado-aw version=1.0.0 source=agents/foo.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/foo.md");
        assert_eq!(meta.version, "1.0.0");
    }

    #[test]
    fn test_parse_header_line_no_marker() {
        assert!(parse_header_line("# Some random comment").is_none());
        assert!(parse_header_line("name: my-pipeline").is_none());
        assert!(parse_header_line("").is_none());
    }

    #[test]
    fn test_parse_header_line_marker_only() {
        // Just the marker with no space after it — should not match
        assert!(parse_header_line("# @ado-aw").is_none());
    }

    #[test]
    fn test_parse_header_line_marker_prefix_mismatch() {
        // "# @ado-aw-v2" should NOT match — must be exact marker + space
        assert!(parse_header_line("# @ado-aw-v2 source=foo.md version=1.0").is_none());
    }

    #[test]
    fn test_parse_header_line_partial() {
        let line = "# @ado-aw source=agents/test.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/test.md");
        assert_eq!(meta.version, "");
    }

    #[test]
    fn test_parse_header_line_quoted_source_with_escaped_quotes() {
        let line = r#"# @ado-aw source="agents/my \"agent\".md" version=0.4.0"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, r#"agents/my "agent".md"#);
        assert_eq!(meta.version, "0.4.0");
    }

    #[test]
    fn test_parse_header_line_arbitrary_source_path() {
        let line = "# @ado-aw source=.azdo/pipelines/review.md version=0.4.0";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, ".azdo/pipelines/review.md");
        assert_eq!(meta.version, "0.4.0");
    }

    #[tokio::test]
    async fn test_detect_pipelines_in_temp_dir() {
        let dir = tempfile::tempdir().unwrap();

        // Write an agentic pipeline YAML
        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/test.md version=0.3.2\n\
                            \n\
                            name: test-pipeline\n";
        tokio::fs::write(dir.path().join("pipeline.yml"), agentic_yaml)
            .await
            .unwrap();

        // Write a non-agentic YAML
        let normal_yaml = "trigger:\n  - main\n\npool:\n  vmImage: ubuntu-latest\n";
        tokio::fs::write(dir.path().join("other.yml"), normal_yaml)
            .await
            .unwrap();

        // Write a non-YAML file
        tokio::fs::write(dir.path().join("readme.md"), "# Hello")
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(
            results[0].yaml_path,
            PathBuf::from("pipeline.yml")
        );
        assert_eq!(results[0].source, "agents/test.md");
        assert_eq!(results[0].version, "0.3.2");
    }

    #[tokio::test]
    async fn test_detect_pipelines_nested_azdo_directory() {
        let dir = tempfile::tempdir().unwrap();

        // .azdo is a common location for ADO pipelines and should be scanned
        let nested = dir.path().join(".azdo").join("pipelines");
        tokio::fs::create_dir_all(&nested).await.unwrap();

        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/nested.md version=1.0.0\n\
                            \n\
                            name: nested-pipeline\n";
        tokio::fs::write(nested.join("agent.yml"), agentic_yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].source, "agents/nested.md");
    }

    #[tokio::test]
    async fn test_detect_pipelines_skips_hidden_dirs() {
        let dir = tempfile::tempdir().unwrap();

        let hidden = dir.path().join(".git");
        tokio::fs::create_dir_all(&hidden).await.unwrap();

        let yaml = "# @ado-aw source=agents/test.md version=0.3.2\nname: test\n";
        tokio::fs::write(hidden.join("config.yml"), yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 0);
    }
}
