//! Agentic pipeline detection.
//!
//! Scans a directory for compiled pipeline YAML files that were generated by `ado-aw`.
//! Detection relies on the `# @ado-aw` header comment that the compiler prepends to all output.

use anyhow::{Context, Result};
use log::{debug, info};
use std::path::{Path, PathBuf};

use crate::compile::HEADER_MARKER;

/// Metadata extracted from an agentic pipeline header comment.
#[derive(Debug, Clone)]
pub struct DetectedPipeline {
    /// Path to the YAML file (relative to the scan root)
    pub yaml_path: PathBuf,
    /// Source markdown file path from the header (e.g., `agents/my-agent.md`)
    pub source: String,
    /// Compiler version that generated this pipeline
    pub version: String,
}

/// Scan a directory for agentic pipeline YAML files.
///
/// Recursively walks `root` looking for `*.yml` and `*.yaml` files whose first
/// few lines contain the `# @ado-aw` marker. Returns metadata extracted from
/// each detected pipeline's header.
pub async fn detect_pipelines(root: &Path) -> Result<Vec<DetectedPipeline>> {
    info!("Scanning for agentic pipelines in: {}", root.display());
    let mut results = Vec::new();
    scan_directory(root, root, &mut results).await?;
    info!("Found {} agentic pipeline(s)", results.len());
    Ok(results)
}

/// Recursively scan a directory, collecting detected pipelines.
fn scan_directory<'a>(
    dir: &'a Path,
    root: &'a Path,
    results: &'a mut Vec<DetectedPipeline>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send + 'a>> {
    Box::pin(async move {
        let mut entries = tokio::fs::read_dir(dir)
            .await
            .with_context(|| format!("Failed to read directory: {}", dir.display()))?;

        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            let file_type = entry.file_type().await?;

            if file_type.is_dir() {
                // Skip hidden directories (except .azdo which commonly contains pipelines)
                // and common non-pipeline directories
                let name = entry.file_name();
                let name_str = name.to_string_lossy();
                if (name_str.starts_with('.') && name_str != ".azdo")
                    || name_str == "node_modules"
                    || name_str == "target"
                {
                    continue;
                }
                scan_directory(&path, root, results).await?;
            } else if file_type.is_file() {
                if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                    if ext == "yml" || ext == "yaml" {
                        if let Some(pipeline) = try_detect_pipeline(&path, root).await? {
                            debug!("Detected agentic pipeline: {}", path.display());
                            results.push(pipeline);
                        }
                    }
                }
            }
        }

        Ok(())
    })
}

/// Check if a YAML file is an agentic pipeline and extract its metadata.
///
/// Reads up to the first 5 lines of the file looking for the `# @ado-aw` marker.
async fn try_detect_pipeline(
    file_path: &Path,
    root: &Path,
) -> Result<Option<DetectedPipeline>> {
    let content = match tokio::fs::read_to_string(file_path).await {
        Ok(c) => c,
        Err(e) => {
            debug!(
                "Skipping {} (read error: {})",
                file_path.display(),
                e
            );
            return Ok(None);
        }
    };

    // Only inspect the first 5 lines for performance
    for line in content.lines().take(5) {
        if let Some(metadata) = parse_header_line(line) {
            let relative_path = file_path
                .strip_prefix(root)
                .unwrap_or(file_path)
                .to_path_buf();

            return Ok(Some(DetectedPipeline {
                yaml_path: relative_path,
                source: metadata.source,
                version: metadata.version,
            }));
        }
    }

    Ok(None)
}

/// Parsed metadata from a `# @ado-aw` header line.
struct HeaderMetadata {
    source: String,
    version: String,
}

/// Parse a single line for the `# @ado-aw` marker and extract key=value pairs.
///
/// Expected format: `# @ado-aw source=agents/foo.md version=1.2.3`
fn parse_header_line(line: &str) -> Option<HeaderMetadata> {
    let line = line.trim();
    if !line.starts_with(HEADER_MARKER) {
        return None;
    }

    let rest = &line[HEADER_MARKER.len()..];
    let mut source = String::new();
    let mut version = String::new();

    for part in rest.split_whitespace() {
        if let Some(val) = part.strip_prefix("source=") {
            source = val.to_string();
        } else if let Some(val) = part.strip_prefix("version=") {
            version = val.to_string();
        }
    }

    if source.is_empty() && version.is_empty() {
        return None;
    }

    Some(HeaderMetadata { source, version })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_header_line_valid() {
        let line = "# @ado-aw source=agents/my-agent.md version=0.3.2";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/my-agent.md");
        assert_eq!(meta.version, "0.3.2");
    }

    #[test]
    fn test_parse_header_line_reordered() {
        let line = "# @ado-aw version=1.0.0 source=agents/foo.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/foo.md");
        assert_eq!(meta.version, "1.0.0");
    }

    #[test]
    fn test_parse_header_line_no_marker() {
        assert!(parse_header_line("# Some random comment").is_none());
        assert!(parse_header_line("name: my-pipeline").is_none());
        assert!(parse_header_line("").is_none());
    }

    #[test]
    fn test_parse_header_line_marker_only() {
        // Just the marker with no key=value pairs
        assert!(parse_header_line("# @ado-aw").is_none());
    }

    #[test]
    fn test_parse_header_line_partial() {
        let line = "# @ado-aw source=agents/test.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/test.md");
        assert_eq!(meta.version, "");
    }

    #[test]
    fn test_parse_header_line_arbitrary_source_path() {
        let line = "# @ado-aw source=.azdo/pipelines/review.md version=0.4.0";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, ".azdo/pipelines/review.md");
        assert_eq!(meta.version, "0.4.0");
    }

    #[tokio::test]
    async fn test_detect_pipelines_in_temp_dir() {
        let dir = tempfile::tempdir().unwrap();

        // Write an agentic pipeline YAML
        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/test.md version=0.3.2\n\
                            \n\
                            name: test-pipeline\n";
        tokio::fs::write(dir.path().join("pipeline.yml"), agentic_yaml)
            .await
            .unwrap();

        // Write a non-agentic YAML
        let normal_yaml = "trigger:\n  - main\n\npool:\n  vmImage: ubuntu-latest\n";
        tokio::fs::write(dir.path().join("other.yml"), normal_yaml)
            .await
            .unwrap();

        // Write a non-YAML file
        tokio::fs::write(dir.path().join("readme.md"), "# Hello")
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(
            results[0].yaml_path,
            PathBuf::from("pipeline.yml")
        );
        assert_eq!(results[0].source, "agents/test.md");
        assert_eq!(results[0].version, "0.3.2");
    }

    #[tokio::test]
    async fn test_detect_pipelines_nested_azdo_directory() {
        let dir = tempfile::tempdir().unwrap();

        // .azdo is a common location for ADO pipelines and should be scanned
        let nested = dir.path().join(".azdo").join("pipelines");
        tokio::fs::create_dir_all(&nested).await.unwrap();

        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/nested.md version=1.0.0\n\
                            \n\
                            name: nested-pipeline\n";
        tokio::fs::write(nested.join("agent.yml"), agentic_yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].source, "agents/nested.md");
    }

    #[tokio::test]
    async fn test_detect_pipelines_skips_hidden_dirs() {
        let dir = tempfile::tempdir().unwrap();

        let hidden = dir.path().join(".git");
        tokio::fs::create_dir_all(&hidden).await.unwrap();

        let yaml = "# @ado-aw source=agents/test.md version=0.3.2\nname: test\n";
        tokio::fs::write(hidden.join("config.yml"), yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 0);
    }
}
