//! Agentic pipeline detection.
//!
//! Scans a directory for compiled pipeline YAML files that were generated by `ado-aw`.
//! Detection relies on the `# @ado-aw` header comment that the compiler prepends to all output.

use anyhow::{Context, Result};
use log::{debug, info};
use std::path::{Path, PathBuf};
use tokio::io::AsyncBufReadExt;

use crate::compile::HEADER_MARKER;

/// Metadata extracted from an agentic pipeline header comment.
#[derive(Debug, Clone)]
pub struct DetectedPipeline {
    /// Path to the YAML file (relative to the scan root)
    pub yaml_path: PathBuf,
    /// Source markdown file path from the header (e.g., `agents/my-agent.md`)
    pub source: String,
    /// Compiler version that generated this pipeline
    pub version: String,
}

/// Scan a directory for agentic pipeline YAML files.
///
/// Recursively walks `root` looking for `*.yml` and `*.yaml` files whose first
/// few lines contain the `# @ado-aw` marker. Returns metadata extracted from
/// each detected pipeline's header.
pub async fn detect_pipelines(root: &Path) -> Result<Vec<DetectedPipeline>> {
    info!("Scanning for agentic pipelines in: {}", root.display());
    let mut results = Vec::new();
    scan_directory(root, root, &mut results).await?;
    info!("Found {} agentic pipeline(s)", results.len());
    Ok(results)
}

/// Recursively scan a directory, collecting detected pipelines.
fn scan_directory<'a>(
    dir: &'a Path,
    root: &'a Path,
    results: &'a mut Vec<DetectedPipeline>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send + 'a>> {
    Box::pin(async move {
        let mut entries = tokio::fs::read_dir(dir)
            .await
            .with_context(|| format!("Failed to read directory: {}", dir.display()))?;

        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            let file_type = entry.file_type().await?;

            if file_type.is_dir() {
                // Skip hidden directories (except .azdo which commonly contains pipelines)
                // and common non-pipeline directories
                let name = entry.file_name();
                let name_str = name.to_string_lossy();
                if (name_str.starts_with('.') && name_str != ".azdo")
                    || name_str == "node_modules"
                    || name_str == "target"
                {
                    continue;
                }
                scan_directory(&path, root, results).await?;
            } else if file_type.is_file() {
                if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                    if ext == "yml" || ext == "yaml" {
                        if let Some(pipeline) = try_detect_pipeline(&path, root).await? {
                            debug!("Detected agentic pipeline: {}", path.display());
                            results.push(pipeline);
                        }
                    }
                }
            }
        }

        Ok(())
    })
}

/// Check if a YAML file is an agentic pipeline and extract its metadata.
///
/// Reads only the first 5 lines of the file for performance — the `@ado-aw`
/// marker is always in the first two lines of compiled output.
async fn try_detect_pipeline(
    file_path: &Path,
    root: &Path,
) -> Result<Option<DetectedPipeline>> {
    let file = match tokio::fs::File::open(file_path).await {
        Ok(f) => f,
        Err(e) => {
            debug!(
                "Skipping {} (open error: {})",
                file_path.display(),
                e
            );
            return Ok(None);
        }
    };

    let reader = tokio::io::BufReader::new(file);
    let mut lines = reader.lines();
    let mut line_count = 0;

    while let Ok(Some(line)) = lines.next_line().await {
        line_count += 1;
        if line_count > 5 {
            break;
        }

        if let Some(metadata) = parse_header_line(&line) {
            let relative_path = file_path
                .strip_prefix(root)
                .unwrap_or(file_path)
                .to_path_buf();

            return Ok(Some(DetectedPipeline {
                yaml_path: relative_path,
                source: metadata.source,
                version: metadata.version,
            }));
        }
    }

    Ok(None)
}

/// Parsed metadata from a `# @ado-aw` header line.
pub struct HeaderMetadata {
    pub source: String,
    pub version: String,
}

/// Parse a single line for the `# @ado-aw` marker and extract key=value pairs.
///
/// Expected format: `# @ado-aw source="path/to/agent.md" version=1.2.3`
///
/// The source value is quoted to support paths with spaces. Unquoted values
/// are also accepted for backward compatibility.
pub fn parse_header_line(line: &str) -> Option<HeaderMetadata> {
    let line = line.trim();
    // Require exact marker followed by a space to avoid matching e.g. "# @ado-aw-v2"
    let rest = line.strip_prefix(HEADER_MARKER)?.strip_prefix(' ')?;

    let mut source = String::new();
    let mut version = String::new();

    let mut remaining = rest;
    while !remaining.is_empty() {
        remaining = remaining.trim_start();
        if let Some(after) = remaining.strip_prefix("source=") {
            // Handle quoted value: source="path with spaces"
            if let Some(after_quote) = after.strip_prefix('"') {
                // Find closing quote, skipping escaped quotes (\")
                let mut value = String::new();
                let mut chars = after_quote.char_indices();
                let mut end_pos = after_quote.len();
                while let Some((i, c)) = chars.next() {
                    if c == '\\' {
                        // Consume the escaped character
                        if let Some((_, escaped)) = chars.next() {
                            value.push(escaped);
                        }
                    } else if c == '"' {
                        end_pos = i;
                        break;
                    } else {
                        value.push(c);
                    }
                }
                source = value;
                remaining = if end_pos < after_quote.len() {
                    &after_quote[end_pos + 1..]
                } else {
                    ""
                };
            } else {
                // Unquoted: take until next whitespace
                let end = after.find(' ').unwrap_or(after.len());
                source = after[..end].to_string();
                remaining = &after[end..];
            }
        } else if let Some(after) = remaining.strip_prefix("version=") {
            let end = after.find(' ').unwrap_or(after.len());
            version = after[..end].to_string();
            remaining = &after[end..];
        } else {
            // Skip unknown token
            let end = remaining.find(' ').unwrap_or(remaining.len());
            remaining = &remaining[end..];
        }
    }

    if source.is_empty() && version.is_empty() {
        return None;
    }

    Some(HeaderMetadata { source, version })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_header_line_valid() {
        let line = "# @ado-aw source=agents/my-agent.md version=0.3.2";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/my-agent.md");
        assert_eq!(meta.version, "0.3.2");
    }

    #[test]
    fn test_parse_header_line_quoted_source() {
        let line = r#"# @ado-aw source="agents/my-agent.md" version=0.3.2"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/my-agent.md");
        assert_eq!(meta.version, "0.3.2");
    }

    #[test]
    fn test_parse_header_line_quoted_source_with_spaces() {
        let line = r#"# @ado-aw source="my agents/my agent.md" version=0.5.0"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "my agents/my agent.md");
        assert_eq!(meta.version, "0.5.0");
    }

    #[test]
    fn test_parse_header_line_reordered() {
        let line = "# @ado-aw version=1.0.0 source=agents/foo.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/foo.md");
        assert_eq!(meta.version, "1.0.0");
    }

    #[test]
    fn test_parse_header_line_no_marker() {
        assert!(parse_header_line("# Some random comment").is_none());
        assert!(parse_header_line("name: my-pipeline").is_none());
        assert!(parse_header_line("").is_none());
    }

    #[test]
    fn test_parse_header_line_marker_only() {
        // Just the marker with no space after it — should not match
        assert!(parse_header_line("# @ado-aw").is_none());
    }

    #[test]
    fn test_parse_header_line_marker_prefix_mismatch() {
        // "# @ado-aw-v2" should NOT match — must be exact marker + space
        assert!(parse_header_line("# @ado-aw-v2 source=foo.md version=1.0").is_none());
    }

    #[test]
    fn test_parse_header_line_partial() {
        let line = "# @ado-aw source=agents/test.md";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, "agents/test.md");
        assert_eq!(meta.version, "");
    }

    #[test]
    fn test_parse_header_line_quoted_source_with_escaped_quotes() {
        let line = r#"# @ado-aw source="agents/my \"agent\".md" version=0.4.0"#;
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, r#"agents/my "agent".md"#);
        assert_eq!(meta.version, "0.4.0");
    }

    #[test]
    fn test_parse_header_line_arbitrary_source_path() {
        let line = "# @ado-aw source=.azdo/pipelines/review.md version=0.4.0";
        let meta = parse_header_line(line).unwrap();
        assert_eq!(meta.source, ".azdo/pipelines/review.md");
        assert_eq!(meta.version, "0.4.0");
    }

    #[tokio::test]
    async fn test_detect_pipelines_in_temp_dir() {
        let dir = tempfile::tempdir().unwrap();

        // Write an agentic pipeline YAML
        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/test.md version=0.3.2\n\
                            \n\
                            name: test-pipeline\n";
        tokio::fs::write(dir.path().join("pipeline.yml"), agentic_yaml)
            .await
            .unwrap();

        // Write a non-agentic YAML
        let normal_yaml = "trigger:\n  - main\n\npool:\n  vmImage: ubuntu-latest\n";
        tokio::fs::write(dir.path().join("other.yml"), normal_yaml)
            .await
            .unwrap();

        // Write a non-YAML file
        tokio::fs::write(dir.path().join("readme.md"), "# Hello")
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(
            results[0].yaml_path,
            PathBuf::from("pipeline.yml")
        );
        assert_eq!(results[0].source, "agents/test.md");
        assert_eq!(results[0].version, "0.3.2");
    }

    #[tokio::test]
    async fn test_detect_pipelines_nested_azdo_directory() {
        let dir = tempfile::tempdir().unwrap();

        // .azdo is a common location for ADO pipelines and should be scanned
        let nested = dir.path().join(".azdo").join("pipelines");
        tokio::fs::create_dir_all(&nested).await.unwrap();

        let agentic_yaml = "# This file is auto-generated by ado-aw. Do not edit manually.\n\
                            # @ado-aw source=agents/nested.md version=1.0.0\n\
                            \n\
                            name: nested-pipeline\n";
        tokio::fs::write(nested.join("agent.yml"), agentic_yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].source, "agents/nested.md");
    }

    #[tokio::test]
    async fn test_detect_pipelines_skips_hidden_dirs() {
        let dir = tempfile::tempdir().unwrap();

        let hidden = dir.path().join(".git");
        tokio::fs::create_dir_all(&hidden).await.unwrap();

        let yaml = "# @ado-aw source=agents/test.md version=0.3.2\nname: test\n";
        tokio::fs::write(hidden.join("config.yml"), yaml)
            .await
            .unwrap();

        let results = detect_pipelines(dir.path()).await.unwrap();
        assert_eq!(results.len(), 0);
    }
}
