//! Add build tag safe output tool

use log::{debug, info};
use percent_encoding::utf8_percent_encode;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::PATH_SEGMENT;
use crate::sanitize::{Sanitize, sanitize as sanitize_text};
use crate::tool_result;
use crate::safeoutputs::{ExecutionContext, ExecutionResult, Executor, Validate};
use anyhow::{Context, ensure};

// ── Stage 1: Params (agent-provided) ──────────────────────────────────────

/// Parameters for adding a tag to an Azure DevOps build
#[derive(Deserialize, JsonSchema)]
pub struct AddBuildTagParams {
    /// Build ID to tag (must be positive)
    pub build_id: i32,
    /// Tag string (1-100 chars, alphanumeric + dashes only)
    pub tag: String,
}

impl Validate for AddBuildTagParams {
    fn validate(&self) -> anyhow::Result<()> {
        ensure!(self.build_id > 0, "build_id must be positive");
        ensure!(!self.tag.is_empty(), "tag must not be empty");
        ensure!(
            self.tag.len() <= 100,
            "tag must be at most 100 characters"
        );
        ensure!(
            self.tag
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-'),
            "tag must contain only alphanumeric characters and dashes"
        );
        Ok(())
    }
}

// ── Stage 1: Result (generated by macro) ──────────────────────────────────

tool_result! {
    name = "add-build-tag",
    write = true,
    params = AddBuildTagParams,
    /// Result of adding a tag to a build
    pub struct AddBuildTagResult {
        build_id: i32,
        tag: String,
    }
}

// ── Stage 2: Sanitization ─────────────────────────────────────────────────

impl Sanitize for AddBuildTagResult {
    fn sanitize_fields(&mut self) {
        self.tag = sanitize_text(&self.tag);
    }
}

// ── Stage 2: Configuration (from front matter) ────────────────────────────

/// Configuration for the add-build-tag tool
/// Example front matter:
/// ```yaml
/// safe-outputs:
///   add-build-tag:
///     allowed-tags:
///       - verified
///       - release-candidate
///     tag-prefix: "agent-"
///     allow-any-build: false
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddBuildTagConfig {
    /// Restrict which tags can be applied. Empty means any tag is allowed.
    /// Supports simple wildcard patterns: entries ending with `*` match by prefix.
    #[serde(default, rename = "allowed-tags")]
    pub allowed_tags: Vec<String>,

    /// Prefix prepended to all tags before applying
    #[serde(default, rename = "tag-prefix")]
    pub tag_prefix: Option<String>,

    /// Whether the agent may tag any build. When false (default), only the
    /// current pipeline build (BUILD_BUILDID) may be tagged.
    #[serde(default, rename = "allow-any-build")]
    pub allow_any_build: bool,
}

impl Default for AddBuildTagConfig {
    fn default() -> Self {
        Self {
            allowed_tags: Vec::new(),
            tag_prefix: None,
            allow_any_build: false,
        }
    }
}

// ── Stage 2: Execution ────────────────────────────────────────────────────

#[async_trait::async_trait]
impl Executor for AddBuildTagResult {
    async fn execute_impl(&self, ctx: &ExecutionContext) -> anyhow::Result<ExecutionResult> {
        info!("Adding tag '{}' to build #{}", self.tag, self.build_id);

        // 1. Extract required context
        let org_url = ctx
            .ado_org_url
            .as_ref()
            .context("AZURE_DEVOPS_ORG_URL not set")?;
        let project = ctx
            .ado_project
            .as_ref()
            .context("SYSTEM_TEAMPROJECT not set")?;
        let token = ctx
            .access_token
            .as_ref()
            .context("No access token available")?;
        debug!("ADO org: {}, project: {}", org_url, project);

        // 2. Get tool-specific configuration
        let config: AddBuildTagConfig = ctx.get_tool_config("add-build-tag");
        debug!("Config: {:?}", config);

        // 2b. Scope check: by default only the current build can be tagged
        if !config.allow_any_build {
            let current_build_id: Option<i32> = std::env::var("BUILD_BUILDID")
                .ok()
                .and_then(|s| s.parse().ok());
            if let Some(current_id) = current_build_id {
                if self.build_id != current_id {
                    return Ok(ExecutionResult::failure(format!(
                        "Build #{} cannot be tagged: only the current build (#{}) is \
                         allowed unless 'allow-any-build: true' is configured",
                        self.build_id, current_id
                    )));
                }
            }
            // If BUILD_BUILDID is not set (e.g. local execution), allow any build
        }

        // 3. Apply tag prefix if configured
        let final_tag = match &config.tag_prefix {
            Some(prefix) => format!("{}{}", prefix, self.tag),
            None => self.tag.clone(),
        };
        debug!("Final tag (after prefix): {}", final_tag);

        // 4. Validate against allowed tags (if non-empty)
        if !config.allowed_tags.is_empty() {
            let allowed = config.allowed_tags.iter().any(|pattern| {
                if let Some(prefix) = pattern.strip_suffix('*') {
                    final_tag.starts_with(prefix)
                } else {
                    *pattern == final_tag
                }
            });
            if !allowed {
                return Ok(ExecutionResult::failure(format!(
                    "Tag '{}' is not in the allowed tags list",
                    final_tag
                )));
            }
        }

        // 5. Build the API URL
        let url = format!(
            "{}/{}/_apis/build/builds/{}/tags/{}?api-version=7.1",
            org_url.trim_end_matches('/'),
            utf8_percent_encode(project, PATH_SEGMENT),
            self.build_id,
            utf8_percent_encode(&final_tag, PATH_SEGMENT),
        );
        debug!("API URL: {}", url);

        // 6. PUT request (empty body)
        let client = reqwest::Client::new();
        info!("Sending PUT to add tag '{}' to build #{}", final_tag, self.build_id);
        let response = client
            .put(&url)
            .basic_auth("", Some(token))
            .send()
            .await
            .context("Failed to send request")?;

        if response.status().is_success() {
            info!(
                "Tag '{}' added to build #{}",
                final_tag, self.build_id
            );

            Ok(ExecutionResult::success_with_data(
                format!(
                    "Added tag '{}' to build #{}",
                    final_tag, self.build_id
                ),
                serde_json::json!({
                    "build_id": self.build_id,
                    "tag": final_tag,
                    "project": project,
                }),
            ))
        } else {
            let status = response.status();
            let error_body = response
                .text()
                .await
                .unwrap_or_else(|_| "Unknown error".to_string());

            Ok(ExecutionResult::failure(format!(
                "Failed to add tag (HTTP {}): {}",
                status, error_body
            )))
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::safeoutputs::ToolResult;

    #[test]
    fn test_result_has_correct_name() {
        assert_eq!(AddBuildTagResult::NAME, "add-build-tag");
    }

    #[test]
    fn test_params_deserializes() {
        let json = r#"{"build_id": 42, "tag": "verified"}"#;
        let params: AddBuildTagParams = serde_json::from_str(json).unwrap();
        assert_eq!(params.build_id, 42);
        assert_eq!(params.tag, "verified");
    }

    #[test]
    fn test_params_converts_to_result() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "release-candidate".to_string(),
        };
        let result: AddBuildTagResult = params.try_into().unwrap();
        assert_eq!(result.name, "add-build-tag");
        assert_eq!(result.build_id, 42);
        assert_eq!(result.tag, "release-candidate");
    }

    #[test]
    fn test_validation_rejects_zero_build_id() {
        let params = AddBuildTagParams {
            build_id: 0,
            tag: "verified".to_string(),
        };
        let result: Result<AddBuildTagResult, _> = params.try_into();
        assert!(result.is_err());
    }

    #[test]
    fn test_validation_rejects_empty_tag() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "".to_string(),
        };
        let result: Result<AddBuildTagResult, _> = params.try_into();
        assert!(result.is_err());
    }

    #[test]
    fn test_validation_rejects_invalid_tag_chars() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "invalid tag!".to_string(),
        };
        let result: Result<AddBuildTagResult, _> = params.try_into();
        assert!(result.is_err());
    }

    #[test]
    fn test_result_serializes_correctly() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "verified".to_string(),
        };
        let result: AddBuildTagResult = params.try_into().unwrap();
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains(r#""name":"add-build-tag""#));
        assert!(json.contains(r#""build_id":42"#));
        assert!(json.contains(r#""tag":"verified""#));
    }

    #[test]
    fn test_config_defaults() {
        let config = AddBuildTagConfig::default();
        assert!(config.allowed_tags.is_empty());
        assert!(config.tag_prefix.is_none());
    }

    #[test]
    fn test_config_deserializes_from_yaml() {
        let yaml = r#"
allowed-tags:
  - verified
  - release-candidate
tag-prefix: "agent-"
"#;
        let config: AddBuildTagConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(config.allowed_tags, vec!["verified", "release-candidate"]);
        assert_eq!(config.tag_prefix, Some("agent-".to_string()));
    }
}
